### ISSUE TITLE
main:app is not available

### ISSUE THREAD

**Issue by aliefe04** [AbduazizZiyodov/ramazon-api#8]
in python 3.11.2 I get errors
ERROR:    Error loading ASGI app. Could not import module "main".

api:api works but it gives other errors

**Comment by AbduazizZiyodov** [comment]
Hello!

Thanks, with `main` I see that I did not update the README file after changing the folder structure. `uvicorn api:api ...` is correct.

About other errors, you have to provide error messages/outputs (your Python version, installed package versions `pip list` etc.). Maybe it is related to Fastapi & pydantic's version, they made huge changes to their source code. I need to sync this project with their current version now.

**Comment by aliefe04** [comment]
are you open to pull requests I can develope this project more

**Comment by aliefe04** [comment]
I used poetry and it does work now

**Comment by AbduazizZiyodov** [comment]
> are you open to pull requests I can develope this project more

Yes, I would be glad. I'm planning to migrate newer versions of FastApi & pydantic.
